### ISSUE TITLE
Custom Fonts Don't Work

### ISSUE THREAD

**Issue by Hexaroot** [IS2511/ChatIS-v2#1]
Hey so I put the font "Monserrat" as the custom font on my stream but it does not show up is there something wrong here?

**Comment by ryantechdev** [comment]
hey its almost 6 months later but you do need to have the font downloaded on your computer, see [Montserrat](https://fonts.google.com/specimen/Montserrat)

also you misspelled the font in your issue comment, maybe that's the reason lol 🙃
